#!/bin/bash

if [[ "$@" == "" ]]; then
    ${0} -h
fi
for i in "$@"
do
case $i in
    -i|--internal)
        ifconfig | grep -Eo 'inet (Adresse:|address:|addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'
    ;;
    -v6|--ipv6)
        ifconfig | grep -Eo 'inet6([[:space:]]|-)?(Adresse|address|addr)?[:]?([[:space:]])?[0-9a-z:]*' | grep -Eo '[0-9A-Za-z]{4}[:]{1}([0-9A-Za-z]*\:){1,10}[0-9A-Za-z]*' | grep -v '::1'
    ;;
    -e|--external)
        curl -s https://4.ifcfg.me/
    ;;
    -u|--update)
        echo "Updating..."
        curl -s https://raw.githubusercontent.com/emazzotta/showip/master/showip > /usr/local/bin/showip
        [[ $? == 0 ]] && echo "Successfully downloaded and installed" || echo "Problem downloading/installing"
    ;;
    -h|--help)
        echo "Usage: ${0} [-e] [-i] [-v6] [-u]"
        echo "Help: Show external or internal IP address."
        echo "Options:"
        echo "  -i, --internal    Show internal IP address. Additional parameter to be grepped for can be specified"
        echo "  -e, --external    Show external IP address."
        echo "  -v6, --ipv6       Show IPv6 address."
        echo "  -u, --update      Update this script."
    ;;
    *)
        echo -e "Unrecognized parameter: ${i}\nTry '$(basename ${0}) --help'"
    ;;
esac
done
